name: Publish VS Code Extension

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install vsce
      run: npm install -g @vscode/vsce

    - name: Publish Extension
      env:
        VSCE_PAT: ${{ secrets.VSCE_TOKEN }}
      run: vsce publish
